### ISSUE TITLE
Is is working?

### ISSUE THREAD

**Issue by ggiacomo** [clipisode/puppeteer-recorder#1]
Hi, this repo looks great but I'm no able to make it work. First error i get is "await is a reserved word". So placed the code inside async function. Than run with babel, i get
`module.exports.record = async function(options) {
                              ^^^^^^^^
SyntaxError: Unexpected token function
`
inside puppeteer-recorder/index.js:4
Also, can you provide an example code with giving an URL to screen? Thank you in advanced

**Comment by maxschmeling** [comment]
What version of node are you using? You'll need to be on a version that supports `async`/`await` natively (7.6.0 or greater) or you'll need to transpile using `babel` (or other transpiler).

**Comment by ggiacomo** [comment]
Thank you for quick response. I solved by updating node and using async function. I'm still missing one point: is it possibile to set an interval time for each screenshot?  If i set for example 25fps, there should be a screenshot every 40milliseconds, otherwise the final video will be superfast, like 1 sec video.
Below my code
```const puppeteer = require("puppeteer");
const {record} = require('puppeteer-recorder');

(async () => {
  const browser = await puppeteer.launch({headless: true});
  let page = await browser.newPage();
  page.setViewport({width: 1000, height: 600, deviceScaleFactor: 2});

  await page.goto("http://www.goodboydigital.com/pixijs/examples/12-2/");
  await record({
    browser: browser, // Optional: a puppeteer Browser instance,
    page: page, // Optional: a puppeteer Page instance,
    output: 'output.webm',
    // output: 'output.mp4',
    fps: 25,
    frames: 25 * 60, // 5 seconds at 60 fps
    prepare: function (browser, page){ /* executed before first capture */
    },
    render: function (browser, page, frame){ /* executed before each capture */
    }
  });
})()
```

**Comment by maxschmeling** [comment]
The `fps` option is used to set the frame rate in the video output. The screenshots will be captured as quickly as possible and passed into `ffmpeg`. The idea is that you can take as much or as little time as you would like rendering each frame and capturing it, but the final video will be at the specified frame rate.

**Comment by ggiacomo** [comment]
Ok, but this way is not correct if you want to capture animations, like the one in the url use in my code, you need to set an interval time for screenshots and use the same fps in ffmpeg. Otherwise the final video will be too slow or too fast. So for example, if you make screenshot every 40milliseconds, you I'll have to pass 1000/40=25fps to ffmpeg

**Comment by maxschmeling** [comment]
@ggiacomo the `render` method renders for a specific frame. It will capture as soon as the render is complete and then repeat for the next frame. This isn't a real-time capture library.

**Comment by GulvarGulp** [comment]
Although I get an output(ouput.webm || .mp4), but this is empty (with 1KB)
I like the puppeteer-recorder approach a lot, but it doesn´t seem to work at this point in time ;(

Or, can you provide a working example? - that would be a huge lift!


prepare
render
render
render
render
render
render
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
