### ISSUE TITLE
This socket has been ended by the other party

### ISSUE THREAD

**Issue by gzlock** [clipisode/puppeteer-recorder#2]
Env:
Mac os 10.13.2
Node.js v9.3.0

ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 9.0.0 (clang-900.0.37)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100

```javascript
//index.js
const puppeteer = require('puppeteer');
// const devices = require('puppeteer/DeviceDescriptors');
// const iPhone = devices['iPhone 6'];
const {record} = require('puppeteer-recorder');

(async () => {
    const browser = await puppeteer.launch({headless: true});
    let page = await browser.newPage();
    page.setViewport({width: 1000, height: 600, deviceScaleFactor: 2});

    await page.goto("http://www.goodboydigital.com/pixijs/examples/12-2/");
    await record({
        browser: browser, // Optional: a puppeteer Browser instance,
        page: page, // Optional: a puppeteer Page instance,
        output: 'output.webm',
        // output: 'output.mp4',
        fps: 25,
        frames: 25 * 60, // 5 seconds at 60 fps
        prepare: function (browser, page){ /* executed before first capture */
        },
        render: function (browser, page, frame){ /* executed before each capture */
        }
    });
})()
```
execute: node index.js
output
```
0|index    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|index    | Error: This socket has been ended by the other party
0|index    |     at Socket.writeAfterFIN [as write] (net.js:365:12)
0|index    |     at Promise (/Users/lock/Documents/screencast/node_modules/puppeteer-recorder/index.js:72:12)
0|index    |     at new Promise (<anonymous>)
0|index    |     at write (/Users/lock/Documents/screencast/node_modules/puppeteer-recorder/index.js:71:3)
0|index    |     at module.exports.record (/Users/lock/Documents/screencast/node_modules/puppeteer-recorder/index.js:44:11)
0|index    |     at <anonymous>
0|index    |     at process._tickCallback (internal/process/next_tick.js:160:7)

```

**Comment by maxschmeling** [comment]
What happens if you don't run in headless mode? This seems like an issue with the connection to Chromium.

**Comment by nodeful** [comment]
Same issue here

**Comment by maxschmeling** [comment]
> Same issue here

Did you try running `{ headless: false }`? Are you running it on your development machine? Is it running against the Chromium version installed with the `puppeteer` package?

**Comment by nodeful** [comment]
Same error in both, headless and not. Running locally on my Mac.
I installed puppeteer separately, before installing your module, so might be a mismatch of versions?
My Chromium version is `Version 65.0.3312.0 (Developer Build) (64-bit)`

**Comment by FlyOrDie** [comment]
Same here :/ 63.0.3239.132 official build. In { headless: false } mode opens a browser, but the error in the console is still the same.

**Comment by FlyOrDie** [comment]
As far as I looked inside the code, `ffmpeg` process is started correctly with args, `puppeteer` manages to create a screenshot, but write function tries to write into `ffmpeg.stdin` and unfortunately fails with this error :/

**Comment by ebidel** [comment]
When I included `recorder({pipeOutput: true})`, ffmpeg was logging "unknown `-auto-alt-ref` flag". 
That flag is added as a vp8 encoding option. Reinstalling ffmeg with libvpx support worked for me:

` brew reinstall ffmpeg --with-libvpx --with-libvorbis`

That should probably be mentioned in the readme.

**Comment by maxschmeling** [comment]
Sorry, I've been very sick the last week. Getting back to it. I'll add the information about `libvpx` to the readme. I'll be pushing several more updates soon also.

I'm open to accepting pull requests for documentation or code if you have the time and want to make an improvement!
