### ISSUE TITLE
This package records audio as well?

### ISSUE THREAD

**Issue by awesomenkj** [clipisode/puppeteer-recorder#3]
Awesome package!

but this records audio as well?

**Comment by maxschmeling** [comment]
The `master` branch of this project will not produce output with audio. I'm working on some experimental changes that, among other things, will allow you to pass in a video file that will be used as an underlay and will also use the audio stream from that video.

**Comment by aalemayhu** [comment]
@maxschmeling is there any update to this? I would love to use it on some websites.

Thanks 🙏

**Comment by Envek** [comment]
Are there any news on audio recording support?
