### ISSUE TITLE
Usage example missing from readme

### ISSUE THREAD

**Issue by marchenko1985** [clipisode/puppeteer-recorder#4]
Hello, I'm trying to figure out is it possible to record a video from a written scenario which open page do something on it, clicking somewhere moving back and forward between pages

From docs it is not clear how it can be done unfortunately, it seems that I can catch concrete page only

**Comment by maxschmeling** [comment]
The `render` option can be an `async` function (returning a `Promise`) and then you can do anything you want in there between frames. But it isn't built to record a "live" session. It's built to record rendered frames. So you have to explicitly control the timing.

**Comment by marchenko1985** [comment]
Ok I see now, it seems that best choice will also be to kind of get screenshots via some timer and then create video from them with ffmpeg, seems like this issue is not related at all to purposes of your project so sorry for inconvenience
